# docker-compose.yml

version: "3.9"

services:
  tradeai_ordu:
    build: .
    container_name: tradeai_ordu
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=tradeai_ordu
      - REDIS_URI=redis://redis:6379/0
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - MAX_PARALLEL_SYMBOL=8
      - ANALYSIS_INTERVAL=60
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    restart: always

# Gelişmiş/opsiyonel: Prometheus, Grafana veya ayrı web panel için ek servisler ekleyebilirsin.
